import { existsSync, readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { defineConfig } from 'vite';
import { externalizeDeps } from 'vite-plugin-externalize-deps';

import importMapInjectorPlugin from '@grasdouble/slm_plugin_vite_import-map-injector';
import reactPreamblePlugin from '@grasdouble/slm_plugin_vite_react-preamble';

import { VENDORS } from './scripts/vendor-config.mjs';
import { PARCELS } from './src/parcels.ts';

const dsPkgPath = resolve(import.meta.dirname, 'node_modules/@grasdouble/lufa_design-system/package.json');
const dsVersion = JSON.parse(readFileSync(dsPkgPath, 'utf8')).version;

/** Reads the vendor manifest generated by build-vendors.mjs (maps name → hashed filename). */
const vendorManifestPath = resolve(import.meta.dirname, 'public/vendor/vendor-manifest.json');
let vendorManifest = {};
if (existsSync(vendorManifestPath)) {
  vendorManifest = JSON.parse(readFileSync(vendorManifestPath, 'utf-8'));
} else {
  console.warn('[vite] ⚠️  public/vendor/vendor-manifest.json not found — run `pnpm build:vendors` first');
}

/** External import map derived from VENDORS — injected in all build modes (dev and prod). */
const externalImportMap = {
  imports: Object.fromEntries(
    VENDORS.flatMap((v) => {
      const filename = vendorManifest[v.name] ?? `${v.name}.mjs`;
      return v.specifiers.map((s) => [s, `/vendor/${filename}`]);
    })
  ),
};

const BASE_URL = 'https://sebastien-lemouillour.fr';

function buildSitemapIndex(entries) {
  const toEntry = ({ loc, lastmod }) =>
    `  <sitemap>\n    <loc>${loc}</loc>\n    <lastmod>${lastmod}</lastmod>\n  </sitemap>`;
  return `<?xml version="1.0" encoding="UTF-8"?>\n<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${entries.map(toEntry).join('\n')}\n</sitemapindex>\n`;
}

/**
 * Emits dist/sitemap.xml as a sitemapindex referencing each parcel's sitemap.
 * Parcel list is shared with main.ts via src/parcels.ts — single source of truth.
 */
const sitemapGeneratorPlugin = () => ({
  name: 'slm-sitemap-generator',
  generateBundle() {
    const today = new Date().toISOString().split('T')[0];
    // Exclude always-active parcels (e.g. header-bar) — they have no public routes.
    const indexEntries = PARCELS.filter((p) => !('alwaysActive' in p)).map(({ name }) => ({
      loc: `${BASE_URL}/${name}/sitemap.xml`,
      lastmod: today,
    }));
    this.emitFile({ type: 'asset', fileName: 'sitemap.xml', source: buildSitemapIndex(indexEntries) });
  },
});

/** Injects %LUFA_DS_VERSION% in index.html so the CDN stylesheet URL always
 *  matches the version installed by pnpm — no manual sync needed. */
const dsVersionPlugin = () => ({
  name: 'lufa-ds-version',
  transformIndexHtml: (html) => html.replaceAll('%LUFA_DS_VERSION%', dsVersion),
});

export default defineConfig({
  plugins: [
    dsVersionPlugin(),
    sitemapGeneratorPlugin(),
    importMapInjectorPlugin({
      extImportMap: externalImportMap,
      devImportMap: 'src/importMap.dev.json',
      previewImportMap: 'src/importMap.preview.json',
      prodImportMap: 'src/importMap.json',
    }),
    externalizeDeps({
      deps: false,
      devDeps: false,
      optionalDeps: false,
      peerDeps: true,
      except: [],
      nodeBuiltins: true,
    }),
    reactPreamblePlugin(),
  ],
  build: {
    target: 'esnext',
    modulePreload: false, // Single-SPA manages the loading of modules
    minify: false,
    rolldownOptions: {
      output: {
        format: 'esm',
        entryFileNames: '[name].[hash].js',
      },
    },
  },
  server: {
    port: 5173,
    cors: true,
    hmr: true,
  },
  preview: {
    port: 5173,
  },
});
