packages:
  - packages/plugins/vite/*
  - packages/cdn/*
  - packages/parcels/*
  - packages/shared
  - packages/slm-container
  - packages/slm-vendors

hoist: false
hoistWorkspacePackages: false

preferWorkspacePackages: true

minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - '@grasdouble/*'

publicHoistPattern:
  - '@storybook/react-vite'
overrides:
  serialize-javascript: ^7.0.5
allowBuilds:
  '@swc/core': true
  '@vscode/vsce-sign': true
  core-js: false
  esbuild: true
  keytar: false
  protobufjs: true
  sharp: true
