import { defineConfig } from 'vitest/config';

export const baseConfig = defineConfig({
  test: {
    environment: 'happy-dom',
    coverage: {
      provider: 'v8',
      reporter: ['text', 'json-summary'],
      include: ['src/**/*.{ts,tsx}'],
      exclude: [
        // Package entry points
        'src/index.ts',
        // Barrel re-export files — convention: index.ts files must only contain re-exports, never logic
        'src/**/index.ts',
        // i18n boilerplate — browser-only init (LanguageDetector, DOM events)
        'src/i18n/**',
        // Test files
        'src/**/*.test.{ts,tsx}',
        // Vite-generated type declarations
        'src/vite-env.d.ts',
        // CSS module type declarations generated by Vite
        'src/**/*.module.css.d.ts',
        // Single-spa parcel entry — registers the parcel with the container
        'src/parcel.tsx',
      ],
      thresholds: {
        autoUpdate: (newThreshold) => Math.floor(newThreshold - 1),
      },
    },
  },
});
