import React from 'react';
import { act, cleanup, render, screen, waitFor } from '@testing-library/react';
import mermaid from 'mermaid';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';

import { MermaidBlock } from '../MermaidBlock';

vi.mock('mermaid', () => ({
  default: {
    initialize: vi.fn(),
    render: vi.fn(),
  },
}));

const mockRender = vi.mocked(mermaid.render);

describe('MermaidBlock — loading state', () => {
  afterEach(cleanup);

  it('shows chart source in a <pre> while rendering', () => {
    mockRender.mockReturnValue(Promise.race([]));

    render(<MermaidBlock chart="graph TD\nA-->B" />);

    const pre = document.querySelector('pre');
    expect(pre).not.toBeNull();
    expect(pre!.textContent).toContain('graph TD');
  });

  it('marks the loading state with aria-busy', () => {
    mockRender.mockReturnValue(Promise.race([]));

    render(<MermaidBlock chart="graph TD\nA-->B" />);

    const pre = document.querySelector('pre');
    expect(pre!.getAttribute('aria-busy')).toBe('true');
  });
});

describe('MermaidBlock — success', () => {
  afterEach(cleanup);

  beforeEach(() => {
    mockRender.mockResolvedValue({
      svg: '<svg style="max-width: 300px;" data-testid="mermaid-svg">diagram</svg>',
      diagramType: 'flowchart',
    });
  });

  it('renders the SVG once mermaid resolves', async () => {
    render(<MermaidBlock chart="graph TD\nA-->B" />);

    await waitFor(() => {
      expect(screen.getByTestId('mermaid-svg')).toBeTruthy();
    });
  });

  it('has role="img" on the diagram container', async () => {
    render(<MermaidBlock chart="graph TD\nA-->B" />);

    await waitFor(() => {
      expect(screen.getByRole('img')).toBeTruthy();
    });
  });

  it('hides the loading <pre> once the SVG is ready', async () => {
    render(<MermaidBlock chart="graph TD\nA-->B" />);

    await waitFor(() => screen.getByTestId('mermaid-svg'));

    expect(document.querySelector('pre')).toBeNull();
  });

  it('preserves the inline style generated by mermaid on the SVG', async () => {
    render(<MermaidBlock chart="graph TD\nA-->B" />);

    await waitFor(() => screen.getByTestId('mermaid-svg'));

    const svg = document.querySelector('svg');
    expect(svg?.getAttribute('style')).toMatch(/max-width:\s*300px/);
  });
});

describe('MermaidBlock — error', () => {
  afterEach(cleanup);

  it('shows the source in a <pre> when mermaid rejects', async () => {
    mockRender.mockRejectedValue(new Error('parse error'));

    render(<MermaidBlock chart="invalid syntax" />);

    await waitFor(() => {
      const pre = document.querySelector('pre');
      expect(pre).not.toBeNull();
      expect(pre!.textContent).toContain('invalid syntax');
    });
  });

  it('does not crash when unmounted before render completes', async () => {
    let reject!: (e: Error) => void;
    mockRender.mockReturnValue(new Promise<never>((_, r) => (reject = r)));

    const { unmount } = render(<MermaidBlock chart="graph TD\nA-->B" />);
    unmount();
    reject(new Error('cancelled'));

    await new Promise((r) => setTimeout(r, 10));
  });
});

describe('MermaidBlock — theming', () => {
  afterEach(() => {
    cleanup();
    document.documentElement.removeAttribute('data-theme');
    document.documentElement.removeAttribute('data-mode');
    vi.mocked(mermaid.initialize).mockClear();
    vi.mocked(mermaid.render).mockClear();
  });

  beforeEach(() => {
    mockRender.mockResolvedValue({
      svg: '<svg data-testid="mermaid-svg">diagram</svg>',
      diagramType: 'flowchart',
    });
  });

  it('initializes mermaid with the base theme', async () => {
    render(<MermaidBlock chart="graph TD\nA-->B" />);

    await waitFor(() => screen.getByTestId('mermaid-svg'));

    expect(mermaid.initialize).toHaveBeenCalledWith(expect.objectContaining({ theme: 'base' }));
  });

  it('re-renders the diagram when lufa-theme-ready fires after a theme switch', async () => {
    render(<MermaidBlock chart="graph TD\nA-->B" />);
    await waitFor(() => screen.getByTestId('mermaid-svg'));

    const callsBefore = vi.mocked(mermaid.render).mock.calls.length;

    act(() => {
      document.documentElement.setAttribute('data-theme', 'matrix');
      document.dispatchEvent(new CustomEvent('lufa-theme-ready'));
    });

    await waitFor(() => {
      expect(vi.mocked(mermaid.render).mock.calls.length).toBeGreaterThan(callsBefore);
    });
  });

  it('re-renders the diagram when data-mode changes', async () => {
    render(<MermaidBlock chart="graph TD\nA-->B" />);
    await waitFor(() => screen.getByTestId('mermaid-svg'));

    const callsBefore = vi.mocked(mermaid.render).mock.calls.length;

    act(() => {
      document.documentElement.setAttribute('data-mode', 'dark');
    });

    await waitFor(() => {
      expect(vi.mocked(mermaid.render).mock.calls.length).toBeGreaterThan(callsBefore);
    });
  });
});
