on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-deploy-prod:
    name: Build and deploy sebastien-lemouillour.fr website
    runs-on: ubuntu-latest
    environment: PROD
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: 'SECRET_GOOGLE_ANALYTICS'
          replace: ${{ secrets.google_analytics }}
          include: 'config.json'
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'
      - run: yarn install
      - run: yarn build
      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.ftp_server }}
          username: ${{ secrets.ftp_username }}
          password: ${{ secrets.ftp_password }}
          local-dir: ./build/
          server-dir: ./
          state-name: ../.ftp-deploy-sync-state.json

  build-deploy-dev:
    name: Build and deploy dev.sebastien-lemouillour.fr website
    runs-on: ubuntu-latest
    environment: DEV
    if: github.ref != 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'
      - run: yarn install
      - run: yarn build
      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.ftp_server }}
          username: ${{ secrets.ftp_username }}
          password: ${{ secrets.ftp_password }}
          local-dir: ./build/
          server-dir: ./
          state-name: ../.ftp-deploy-sync-state.json
