name: Global:Release:Changesets

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions: {}

jobs:
  Changesets-release:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: write
      packages: write
      pull-requests: write
      issues: read
      checks: read
      statuses: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          token: ${{ github.token }}
          persist-credentials: false

      - name: Setup Node.js and pnpm
        uses: grasdouble/Lufa-CICD/actions/setup-node-pnpm@setup-node-pnpm-v1
        with:
          node-version-file: '.tool-versions'
          github-token: ${{ secrets.LUFA_CI_SECRET_WRITE }}

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build packages
        run: pnpm all:build

      - name: Version or publish packages
        uses: grasdouble/Lufa-CICD/actions/changesets-release@changesets-release-v2
        with:
          release-token: ${{ secrets.LUFA_CI_SECRET_WRITE }}
