name: SLM:Publish-to-Prod:Container
# Publish SLM Container to production via FTP.

on:
  workflow_dispatch:

permissions: {}

jobs:
  deploy:
    name: Deploy to production
    runs-on: ubuntu-latest
    environment: 'MF_Container'
    permissions:
      contents: read
      deployments: write
      packages: read
    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v7

      - name: 📦 Setup Node.js and pnpm
        uses: grasdouble/Lufa-CICD/actions/setup-node-pnpm@setup-node-pnpm-v1
        with:
          node-version-file: '.tool-versions'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: 📦 Install dependencies
        run: pnpm install --frozen-lockfile

      - name: 🏗️ Build SLM container
        shell: bash
        env:
          VITE_GOOGLE_ANALYTICS_ID: ${{ secrets.VITE_GOOGLE_ANALYTICS_ID }}
        run: |
          pnpm all:build

      - name: 📂 Deploy to FTP
        uses: grasdouble/Lufa-CICD/actions/ftp-deploy@ftp-deploy-v1
        with:
          server: ${{ secrets.MF_FTP_URL }}
          port: ${{ secrets.MF_FTP_PORT }}
          protocol: ${{ secrets.MF_FTP_PROTOCOL }}
          username: ${{ secrets.MF_FTP_LOGIN }}
          password: ${{ secrets.MF_FTP_PWD }}
          local-dir: './packages/slm-container/dist/'
          exclude: |
            .well-known/**
            cgi-bin/**
            .ftpquota
            .htaccess
